sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 3.1
services: docker
before_install:
  - cd 02_RestWithAsp-NET5_QuatroVerbos/RestWithAsp-NET5
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-asp-net5:latest $DOCKER_USERNAME/rest-with-asp-net5:$TRAVIS_JOB_ID;
    docker tag rest-with-asp-net5-db:latest $DOCKER_USERNAME/rest-with-asp-net5-db:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net5:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net5-db:$TRAVIS_JOB_ID;
  on:
    brach: master
notifications:
  email: false