version: '3.4'

services:
  rest-with-asp-net5:
    image: rest-with-asp-net5:dev
    container_name: RestWithAsp-NET5
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RestWithAsp-NET5"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_rest-with-asp-net5$
    volumes:
      - C:\Users\lucas.jose\Documents\udemy\RestWithAsp-NET5\05_RestWithAsp-NET5_QuatroVerbos_Node\backend\RestWithAsp-NET5:/app
      - C:\Users\lucas.jose\Documents\udemy\RestWithAsp-NET5\05_RestWithAsp-NET5_QuatroVerbos_Node\backend:/src
      - C:\Users\lucas.jose\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_rest-with-asp-net5$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_rest-with-asp-net5$ \"/src/../../02_RestWithAsp-NET5_QuatroVerbos/RestWithAsp-NET5/bin/Debug/net5.0/RestWithAsp-NET5.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true